import { PermissionFlagsBits } from "discord.js";

import type { ModuleManifest } from "../../core/modules/types.js";

export const moderationManifest = {
  id: "moderation",
  name: "Moderation",
  description: "User-centered cases, staff actions, evidence, channel controls, notifications, and audit records.",
  version: "2.0.0",
  icon: "🛡️",
  defaultEnabled: false,
  features: [
    { id: "bans", name: "Bans", description: "Ban and unban users.", defaultEnabled: true, requiredBotPermissions: [PermissionFlagsBits.BanMembers] },
    { id: "cases", name: "Cases", description: "Keep one durable moderation case per user.", defaultEnabled: true },
    { id: "evidence", name: "Evidence", description: "Manage case-wide and entry-linked evidence.", defaultEnabled: true, dependencies: ["cases"] },
    { id: "kicks", name: "Kicks", description: "Remove members from the server.", defaultEnabled: true, requiredBotPermissions: [PermissionFlagsBits.KickMembers] },
    { id: "nickname", name: "Nickname", description: "Change or reset member nicknames.", defaultEnabled: true, requiredBotPermissions: [PermissionFlagsBits.ManageNicknames] },
    { id: "purge", name: "Purge", description: "Preview and delete matching messages safely.", defaultEnabled: true, requiredBotPermissions: [PermissionFlagsBits.ManageMessages] },
    { id: "slowmode", name: "Slowmode", description: "Configure text-channel rate limits.", defaultEnabled: true, requiredBotPermissions: [PermissionFlagsBits.ManageChannels] },
    { id: "sudo", name: "Sudo", description: "Allow authorized staff to send messages through the bot.", defaultEnabled: true, requiredBotPermissions: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages] },
    { id: "timeouts", name: "Timeouts", description: "Apply and remove Discord timeouts.", defaultEnabled: true, requiredBotPermissions: [PermissionFlagsBits.ModerateMembers] },
    { id: "warnings", name: "Warnings", description: "Issue formal staff warnings.", defaultEnabled: true },
    { id: "user-management", name: "User Management", description: "Open user dashboards and filtered case views.", defaultEnabled: true, dependencies: ["cases"] },
    { id: "audit-log", name: "Audit Log", description: "Record moderation or full server-management events.", defaultEnabled: true, requiredBotPermissions: [PermissionFlagsBits.ViewAuditLog] },
    { id: "channel-locks", name: "Channel Locks", description: "Lock channels while preserving prior overwrites.", defaultEnabled: true, requiredBotPermissions: [PermissionFlagsBits.ManageChannels] },
    { id: "user-notifications", name: "User Notifications", description: "Send branded moderation notices by DM.", defaultEnabled: true },
    { id: "moderation-log", name: "Moderation Log", description: "Publish polished bot-action summaries for staff.", defaultEnabled: true },
  ],
  config: [
    { key: "moderationLogChannelId", label: "Moderation Log", description: "Staff channel for bot moderation summaries.", type: "channel", defaultValue: null, category: "channels", setup: true, requiredWhen: { featureId: "moderation-log", enabled: true } },
    { key: "auditLogChannelId", label: "Audit Log", description: "Private channel for administrative audit events.", type: "channel", defaultValue: null, category: "channels", setup: true, requiredWhen: { featureId: "audit-log", enabled: true } },
    { key: "caseCategoryId", label: "Case Category", description: "Optional category for private case discussion channels.", type: "category", defaultValue: null, category: "channels" },
    { key: "moderatorRoleIds", label: "Moderator Roles", description: "Roles that bypass ordinary user-side moderation permission checks.", type: "role-list", defaultValue: [], category: "roles", setup: true },
    { key: "rulesUrl", label: "Rules URL", description: "Optional server-rules link included in user notices.", type: "url", defaultValue: null, category: "notifications" },
    { key: "auditScope", label: "Audit Scope", description: "Choose moderation events only or full server management.", type: "enum", defaultValue: "moderation", category: "audit", setup: true, choices: [{ name: "Moderation Only", value: "moderation" }, { name: "Full Server Management", value: "full" }] },
    { key: "purgeConfirmationThreshold", label: "Purge Confirmation Threshold", description: "Matched message count that requires explicit confirmation.", type: "integer", defaultValue: 25, min: 1, max: 1000, category: "purge" },
    { key: "purgeScanLimit", label: "Purge Scan Limit", description: "Maximum messages scanned across selected channels.", type: "integer", defaultValue: 1000, min: 100, max: 5000, category: "purge" },
  ],
  capabilities: [],
  docs: [
    { id: "overview", title: "Moderation Overview", category: "Moderation", summary: "Features, roles, and the unified case system.", body: "Moderation features are enabled independently per server. Native Discord permissions, Moderator roles, and Bot Admin roles are resolved at runtime.", keywords: ["moderation", "features"] },
    { id: "cases", title: "Cases and Case Entries", category: "Moderation", summary: "One case per user with a chronological timeline.", body: "A server has at most one case per target user. Warnings, timeouts, kicks, bans, reversals, and manual records append entries to that case. Cases have no status.", keywords: ["case", "entries", "history"] },
    { id: "evidence", title: "Evidence", category: "Moderation", summary: "Case-wide evidence with optional entry links and results.", body: "Evidence is plain content with an optional description and moderation result. It can be added, edited, paged, and deleted from the case interface.", keywords: ["evidence", "result"] },
    { id: "custom-types", title: "Custom Case Types", category: "Moderation", summary: "Guild-specific manual classifications.", body: "Custom types have stable IDs, aliases, a color, and an emoji. Slash-command autocomplete searches names and aliases without changing global commands.", keywords: ["type", "alias", "autocomplete"] },
    { id: "actions", title: "Ban, Kick, Timeout, and Warn", category: "Commands", summary: "Serious user moderation actions.", body: "Serious actions require reasons. When Cases is enabled they append an entry; when User Notifications is enabled they send a DM. Silent actions do neither, but still write a private audit record.", keywords: ["ban", "kick", "timeout", "warn", "silent"] },
    { id: "administration", title: "Nickname, Slowmode, Sudo, Locks, and Purge", category: "Commands", summary: "Administrative moderation tools.", body: "Nickname and slowmode do not create user cases or require reasons. /sudo sends mention-safe messages through the bot for authorized staff. Purge uses bounded scans, preview, confirmation, and accurate API result counts.", keywords: ["nickname", "slowmode", "sudo", "purge", "lock"] },
    { id: "users", title: "User Management", category: "Moderation", summary: "Account information and filtered moderation views.", body: "The user dashboard and warn, timeout, kick, and ban views all query the same user case and entries.", keywords: ["user", "dashboard"] },
    { id: "audit", title: "Audit Log Modes", category: "Moderation", summary: "Moderation-only and full server-management scopes.", body: "Moderation Only records bot and moderation events. Full Server Management additionally follows meaningful Discord administrative audit events and deduplicates by source event ID.", keywords: ["audit", "full"] },
    { id: "permissions", title: "Moderation Permissions", category: "Permissions", summary: "Native, Moderator, and Bot Admin authorization.", body: "A command is allowed by its native Discord permission, a configured Moderator role, a configured Bot Admin role, or owner/Administrator access. Bot permissions and role hierarchy are always enforced separately.", keywords: ["roles", "permissions"] },
    { id: "resets", title: "Resetting Moderation", category: "Configuration", summary: "Case-only and full-server reset behavior.", body: "Case reset removes cases, entries, evidence, types, and counters while preserving setup. /resetsetup transactionally removes setup, configuration, and every module's guild data.", keywords: ["reset", "resetsetup"] },
  ],
} as const satisfies ModuleManifest;
